#! /bin/bash

# shellcheck disable=SC2223
# shellcheck disable=SC2128
# shellcheck disable=SC2086
: ${PROG:=$(basename ${BASH_SOURCE})}

_cli_bash_autocomplete() {
  if [[ "${COMP_WORDS[0]}" != "source" ]]; then
    # shellcheck disable=SC2034
    local cur opts base
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    if [[ "$cur" == "-"* ]]; then
      # shellcheck disable=SC2068
      opts=$(${COMP_WORDS[@]:0:$COMP_CWORD} ${cur} --generate-bash-completion)
    else
      # shellcheck disable=SC2068
      opts=$(${COMP_WORDS[@]:0:$COMP_CWORD} --generate-bash-completion)
    fi
    # shellcheck disable=SC2207
    COMPREPLY=($(compgen -W "${opts}" -- ${cur}))
    return 0
  fi
}

complete -o bashdefault -o default -o nospace -F _cli_bash_autocomplete $PROG
unset PROG
